name: Run 4 R Scripts in Parallel

on:
  workflow_dispatch:

jobs:
  run-r-scripts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [2, 3, 4, 5]

    name: Run main_script${{ matrix.script }}.R
    steps:
      - uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("spatial", "spatstat", "igraph", "dplyr"), repos = "https://cloud.r-project.org")'

      - name: Run main_script${{ matrix.script }}.R
        run: Rscript main_script${{ matrix.script }}.R

      - name: Upload data_lambda_${{ matrix.script }}.rds
        uses: actions/upload-artifact@v4
        with:
          name: result-${{ matrix.script }}
          path: data_lambda_${{ matrix.script }}.rds
