name: Run 5 R Scripts in Parallel

on:
  workflow_dispatch:  # Allows manual run

jobs:
  run-r-scripts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [2, 3, 4, 5]

    name: Run main_script${{ matrix.script }}.R
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("spatial", "spatstat", "igraph", "dplyr"), repos = "https://cloud.r-project.org")'

      - name: Run main_script${{ matrix.script }}.R
        run: Rscript main_script${{ matrix.script }}.R

      - name: List all .rds files created by script${{ matrix.script }}
        run: find outputs/script${{ matrix.script }} -type f

      - name: Upload all .rds files from script${{ matrix.script }}
        uses: actions/upload-artifact@v4
        with:
          name: result-${{ matrix.script }}
          path: outputs/script${{ matrix.script }}/
