name: Run Multiple R Scripts in Parallel

on:
  workflow_dispatch:  # Trigger manually from the GitHub Actions tab

jobs:
  run-r-scripts:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        script: [2, 3, 4, 5]  # Add more if needed

    name: Run main_script${{ matrix.script }}.R
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install required R packages
        run: |
          Rscript -e 'install.packages(c("spatial", "spatstat", "igraph", "dplyr"), repos = "https://cloud.r-project.org")'

      - name: Run R script main_script${{ matrix.script }}.R
        run: Rscript main_script${{ matrix.script }}.R

      - name: List output files for script${{ matrix.script }}
        run: |
          echo "Output files:"
          find outputs/script${{ matrix.script }} -type f || echo "No output files found."

      - name: Upload artifacts for script${{ matrix.script }}
        uses: actions/upload-artifact@v4
        with:
          name: results-script${{ matrix.script }}
          path: outputs/script${{ matrix.script }}/
